import { mkdirSync, readFileSync, renameSync, rmSync, writeFileSync, existsSync, statSync } from "node:fs";
import { join } from "node:path";
import {
  DATA_DIR,
  MANIFEST_PATH,
  RUNTIME_DIR,
  SNAPSHOT_PATH,
  findBinary,
  findCore,
} from "./paths.ts";

/**
 * The only module that runs Factorio, and the reason the read-only claim holds.
 *
 * `--dump-data` writes `script-output/data-raw-dump.json` under the engine's
 * write-data directory, which defaults to ~/.factorio. We generate a config that
 * points write-data at .factorio-runtime/ inside this project instead, so the
 * engine writes only where we own the disk. read-data still points at the real
 * install, so the dump is the genuine prototype set.
 *
 * A fresh write-data means a freshly generated mod-list.json, which enables the
 * shipped base mods (base, elevated-rails, quality, space-age) and nothing else.
 * That is exactly a vanilla Space Age snapshot, independent of what the player
 * happens to have installed.
 */

export interface Manifest {
  gameVersion: string;
  build: string;
  mods: Array<{ name: string; version: string }>;
  dumpedAt: string;
  bytes: number;
  core: string;
}

export function writeRuntimeConfig(core: string): string {
  const configDir = join(RUNTIME_DIR, "config");
  mkdirSync(configDir, { recursive: true });
  const configPath = join(configDir, "config.ini");
  const ini = [
    "; Generated by factorio-advisor. Redirects the engine's write-data into this",
    "; project so that a data dump never touches the player's ~/.factorio.",
    "[path]",
    `read-data=${join(core, "data")}`,
    `write-data=${RUNTIME_DIR}`,
    "",
    "[general]",
    "locale=en",
    "",
  ].join("\n");
  writeFileSync(configPath, ini);
  return configPath;
}

/** Pull version and mod set out of the run's log rather than guessing them. */
function parseLog(log: string): Pick<Manifest, "gameVersion" | "build" | "mods"> {
  const version = /Factorio\s+([\d.]+)\s+\(build\s+(\d+)/.exec(log);
  const mods: Array<{ name: string; version: string }> = [];
  const seen = new Set<string>();
  const modRe = /Loading mod (\S+) ([\d.]+) \(data\.lua\)/g;
  for (let m = modRe.exec(log); m; m = modRe.exec(log)) {
    const name = m[1]!;
    if (seen.has(name)) continue;
    seen.add(name);
    mods.push({ name, version: m[2]! });
  }
  return {
    gameVersion: version?.[1] ?? "unknown",
    build: version?.[2] ?? "unknown",
    mods,
  };
}

export async function sync(opts: { quiet?: boolean } = {}): Promise<Manifest> {
  const core = findCore();
  const binary = findBinary(core);
  const configPath = writeRuntimeConfig(core);

  const say = (s: string) => {
    if (!opts.quiet) console.log(s);
  };
  say(`Running ${binary} --dump-data`);
  say(`  read-data  ${join(core, "data")}`);
  say(`  write-data ${RUNTIME_DIR}   (the player's user dir is not touched)`);

  const proc = Bun.spawn([binary, "--config", configPath, "--dump-data"], {
    cwd: RUNTIME_DIR,
    stdout: "pipe",
    stderr: "pipe",
  });
  const [stdout, stderr] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
  ]);
  const code = await proc.exited;
  const log = stdout + stderr;
  if (code !== 0) {
    throw new Error(`factorio --dump-data exited ${code}\n${log.slice(-2000)}`);
  }

  const produced = join(RUNTIME_DIR, "script-output", "data-raw-dump.json");
  if (!existsSync(produced)) {
    throw new Error(
      `factorio reported success but wrote no dump at ${produced}\n${log.slice(-2000)}`,
    );
  }

  mkdirSync(DATA_DIR, { recursive: true });
  // Move rather than copy: 27 MB, and the runtime dir is scratch.
  rmSync(SNAPSHOT_PATH, { force: true });
  renameSync(produced, SNAPSHOT_PATH);
  const bytes = statSync(SNAPSHOT_PATH).size;

  const manifest: Manifest = {
    ...parseLog(log),
    dumpedAt: new Date().toISOString(),
    bytes,
    core,
  };
  writeFileSync(MANIFEST_PATH, JSON.stringify(manifest, null, 2) + "\n");
  say(
    `Snapshot: Factorio ${manifest.gameVersion} (build ${manifest.build}), ` +
      `${manifest.mods.length} mods, ${(bytes / 1e6).toFixed(1)} MB`,
  );
  return manifest;
}

export function readManifest(): Manifest | null {
  try {
    return JSON.parse(readFileSync(MANIFEST_PATH, "utf8")) as Manifest;
  } catch {
    return null;
  }
}
